site_name: "camundactl"
site_description: "camunda command line interface like kubectl"
site_url: "http://camundactl.github.io"
repo_url: "http://github.com/jblawatt/camundactl"

dev_addr: localhost:9090

nav:
  - Home:
      - Overview: index.md
      - Examples: examples.md
      - Configuration: configuration.md
      - Usage: usage.md
      - Output: output.md
      - Full Reference:
          - get Commands: commands/get.md
          - apply Commands: commands/apply.md
          - delete Commands: commands/delete.md
          - describe Commands: commands/describe.md
          - Other Commands: commands/others.md
  - API Doc: api_doc.md

# https://python-markdown.github.io/extensions/
markdown_extensions:
  - attr_list
  - mkdocs-click
  - toc:
      permalink: True
  - plantuml_markdown:
      server: http://www.plantuml.com/plantuml
  - pymdownx.highlight
  - pymdownx.superfences

plugins:
  - search
  - mkdocstrings:
      watch:
        - camundactl
  - gen-files:
      scripts:
        - docs/gen_api_doc.py

theme:
  name: material
  locale: en
  hightlightjs: true
  palette:
    primary: deep orange
    accent: deep orange
