name: Run unittests
on: [push]

jobs:
  build:
    name: Run unittests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout main

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install Dependencies
        run: |
          python -m pip install poetry
          python -m poetry export -f requirements.txt --without-hashes --dev > requirements.txt
          python -m pip install -r requirements.txt
          python -m pip install pytest
      - name: Test
        run: |
           pytest --cov=camundactl .
