name: Run unittests
on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout main

      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install Dependencies
        run: |
          python -m pip install poetry
          python -m poetry install --dev
      - name: Test
        run: |
           python -m pytest --cov=camundactl 
